# Generated by Django 4.1.5 on 2023-05-06 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_userprofile_delete_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
